# Site settings
name: David Robert
description: ""
url: "davidrobert.github.io"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  davidrobert
codepen_username: 
facebook_username: 
vk_username: 
twitter_username: while42
google_plus_username: 
linkedin_username: davidrobert
vine_username:  
instagram_username:  
flickr_username: 
steam_username: 
soundcloud_username: 
stack_of_username: 
reddit_username: 
medium_username: 
tumblr_username: 
weibo_username: 
lastfm_username: 
blog_url: 
email: davidrobert@gmail.com
public_key_url: 


avatar: no
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
